export const FETCH_GEOLOCATION_START: string = 'FETCH_GEOLOCATION_START';
export const FETCH_GEOLOCATION_SUCCESS: string = 'FETCH_GEOLOCATION_SUCCESS';
export const FETCH_GEOLOCATION_FAILURE: string = 'FETCH_GEOLOCATION_FAILURE';
export const HIDE_GEOLOCATION_MSG: string = 'HIDE_GEOLOCATION_MSG';

export const FETCH_WEATHER_START: string = 'FETCH_WEATHER_START';
export const FETCH_WEATHER_SUCCESS: string = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAILURE: string = 'FETCH_WEATHER_FAILURE';
export const HIDE_WEATHER_MSG: string = 'HIDE_WEATHER_MSG';

export const CHANGE_UNIT_FORMAT: string = 'CHANGE_UNIT_FORMAT';
