export const FETCH_GEOLOCATION_START: string = 'FETCH_GEOLOCATION_START';
export const FETCH_GEOLOCATION_SUCCESS: string = 'FETCH_GEOLOCATION_SUCCESS';
export const FETCH_GEOLOCATION_FAILURE: string = 'FETCH_GEOLOCATION_FAILURE';

export const FETCH_WEATHER_START: string = 'FETCH_WEATHER_START';
export const FETCH_WEATHER_SUCCESS: string = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAILURE: string = 'FETCH_WEATHER_FAILURE';

export const CHANGE_UNIT_FORMAT: string = 'CHANGE_UNIT_FORMAT';
